// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnW8aVwgYbmmjE6l4qPVhPSokkU91jPZE',
    appId: '1:688440273443:web:dc4cc6d4b05d8fb360df96',
    messagingSenderId: '688440273443',
    projectId: 'example-firebase-6096e',
    authDomain: 'example-firebase-6096e.firebaseapp.com',
    storageBucket: 'example-firebase-6096e.appspot.com',
    measurementId: 'G-C9499KNSK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYSIwhYUut96ana1OdZ4h1mkbB6CWJMfY',
    appId: '1:688440273443:android:5a0f098b44eb325660df96',
    messagingSenderId: '688440273443',
    projectId: 'example-firebase-6096e',
    storageBucket: 'example-firebase-6096e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF1_1taszYsBnX-DOORwh4fT8fjD0-jbs',
    appId: '1:688440273443:ios:46de1c1b62d5934f60df96',
    messagingSenderId: '688440273443',
    projectId: 'example-firebase-6096e',
    storageBucket: 'example-firebase-6096e.appspot.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF1_1taszYsBnX-DOORwh4fT8fjD0-jbs',
    appId: '1:688440273443:ios:d26a6bd330b467db60df96',
    messagingSenderId: '688440273443',
    projectId: 'example-firebase-6096e',
    storageBucket: 'example-firebase-6096e.appspot.com',
    iosBundleId: 'com.example.firebaseExample.RunnerTests',
  );
}
